function y = filter1(x)
%FILTER1 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 17-Jan-2019 10:34:49

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
	
	% The following code was used to design the filter coefficients:
	%
	% N     = 8;    % Order
	% F3dB1 = 1;    % First
	% F3dB2 = 10;   % Second
	% Fs    = 100;  % Sampling Frequency
	%
	% h = fdesign.bandpass('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);
	%
	% Hd = design(h, 'butter', ...
	%     'SystemObject', true);
	
	Hd = dsp.BiquadFilter( ...
		'Structure', 'Direct form II', ...
		'SOSMatrix', [1 0 -1 1 -1.37683900865519 0.687349537180752; 1 0 -1 1 ...
		-1.95571501783574 0.959743666947109; 1 0 -1 1 -1.87107659753127 ...
		0.876376802975336; 1 0 -1 1 -1.19516446274824 0.385402006449349], ...
		'ScaleValues', [0.254148445694598; 0.254148445694598; ...
		0.228172887439899; 0.228172887439899; 1]);
end

s = double(x);
y = step(Hd,s);


