%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Documents\PhD\Edmonton\data\data.xlsx
%    Worksheet: E4_1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/08 17:06:28

%% Import the data
[~, ~, raw] = xlsread('D:\Documents\PhD\Edmonton\data\data.xlsx','E4_1','A2:H8193');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;