function testFileOpen
    tab_group = uitabgroup( 'Units', 'normalized', ...
            'Position', [0 0, 1, 1], 'SelectionChangedFcn', @tab_changed_callback);
%     open_button = uicontrol('Parent', tab_group, 'Style', 'pushbutton', ...
%             'Units', 'normalized', 'Position', [0.95 0.95 0.05 0.05], ...
%             'Callback', open_file_callback, 'String', 'Open', ...
%             'ToolTipString', 'Open'); %#ok<NASGU>
    save_button = uicontrol('Parent', tab_group, 'Style', 'pushbutton', ...
        'Units', 'normalized', 'Position', [0.95 0.98 0.05 0.02], ...
        'Callback', @savebutton_callback, 'String', 'Save Data', ...
        'ToolTipString', 'Save'); %#ok<NASGU>
end
   
function open_file_callback(hObject, ~)
    disp('GUZ');
end

function savebutton_callback(hObject, ~)
    disp('guz');
end