global OUTPUT
base_file = 'D:\Documents\PhD\FieldStudies\SaudiData\SaudiSHARQ\OUT\0.5Hz\EG1\';
test_name = 'Test1';
for idx = [3]
    source_file = OUTPUT.Data{idx}.FileName(1:end-5);
    file = [base_file test_name '_' source_file];
%     writetable(OUTPUT.Data{idx}.DATA.App, [file '_App.xlsx'], ...
%         'WriteRowNames', true)
%     writetable(OUTPUT.Data{idx}.DATA.Vpp, [file '_Vpp.xlsx'], ...
%         'WriteRowNames', true)
%     writetable(OUTPUT.Data{idx}.DATA.Dpp, [file '_Dpp.xlsx'], ...
%     'WriteRowNames', true)

    tbl = [OUTPUT.Data{idx}.DATA.Time OUTPUT.Data{idx}.DATA.Acceleration];
    tbl = array2table(tbl);
    writetable(tbl, [file '.xlsx'], 'Sheet', 'Acceleration');
    xlswrite([file '.xlsx'], ['Time[s]', ...
        cellfun(@(c) strcat(c, '[m/s^2]'), ...
        OUTPUT.Sensor_configuration.ChannelNames, 'uni', 0)], ...
        'Acceleration', 'A1');
    
    tbl = [OUTPUT.Data{idx}.DATA.Time OUTPUT.Data{idx}.DATA.Velocity];
    tbl = array2table(tbl);
    writetable(tbl, [file '.xlsx'], 'Sheet', 'Velocity');
    xlswrite([file '.xlsx'], ['Time[s]', ...
        cellfun(@(c) strcat(c, '[mm/s]'), ...
        OUTPUT.Sensor_configuration.ChannelNames, 'uni', 0)], ...
        'Velocity', 'A1');
    
    tbl = [OUTPUT.Data{idx}.DATA.Time OUTPUT.Data{idx}.DATA.Displacement];
    tbl = array2table(tbl);
    writetable(tbl, [file '.xlsx'], 'Sheet', 'Displacement');
    xlswrite([file '.xlsx'], ['Time[s]', ...
        cellfun(@(c) strcat(c, '[mm]'), ...
        OUTPUT.Sensor_configuration.ChannelNames, 'uni', 0)], ...
        'Displacement', 'A1');
end